---
- hosts: all
  user: root
    tasks:

      - name: stop jenkins
        service: name=jenkins state=stopped


      - name : install jenkins
        command: sudo apt-get install jenkins -y
										    
