--- 
- name: Testing email
  hosts: all
  tasks: 
    - name: Send email
      local_action: mail
        host=127.0.0.1
        port:25
        subject="Ansible test mail"
        body="Testing email"
        from="srikanth.challa@bestbuy.com"
        to="srikanth.challa@bestbuy.com"
        charset=utf8
