---
- name: remove jenkins server
  hosts: all
  gather_facts: false
  user: "{{ uservar }}"
  tasks:
      - name: remove jenkins server
        command: curl -v -X DELETE http://192.168.33.11:8080/
        
