---
- name: remove jenkins server
  hosts: all
  gather_facts: false
  user: "{{ uservar }}"
  sudo: true
  tasks:
      - name: REST to remove jenkins server from a discovery service
        command: curl -X rm "http://192.168.33.11:8080"
