---
- name: remove jenkins server
  hosts: all
  gather_facts: false
  user: "{{ uservar }}"
  sudo: true
  tasks:
      - uri: url=http://{{jenkins.host}}/job/{{jenkins.job}}/build?token={{jenkins.token}}
       "method=GET" user={{jenkins.user}} password={{jenkins.password}} force_basic_auth=yes status_code=201
