---
- name: remove jenkins server
  hosts: all
  gather_facts: false
  user: "{{ uservar }}"
  tasks:
      - name: remove jenkins server
        wait_for: host={{ inventory_hostname }} port=22 state=absent
        connection: local
        sudo: false
