---
- name: remove jenkins server
  hosts: all
  gather_facts: false
  user: "{{ uservar }}"
  sudo: true
  tasks:
      - name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents.
      - action: uri url=http://192.168.33.11 return_content=yes
        register: webpage

      - action: fail
        when: 'AWESOME' not in "{{ webpage.content }}"
