---
- name: remove jenkins server
  hosts: all
  gather_facts: false
  user: "{{ uservar }}"
  tasks:
      - name: remove jenkins server
        action: remove host={{ inventory_hostname }} port=8080
        
