---
- hosts: all
  user: root
  tasks:

    - name: start jenkins
      service: name=jenkins state=started
 
    - name: this command prints FAILED when it fails
      command: /usr/bin/example-command -x -y -z
      register: command_result
      failed_when: "'FAILED' in command_result.stderr"
