---
- name: Backup Tower and Restore to Second Host 
  hosts: 192.168.33.10
  sudo: true
  vars:
    restore: no
    pulldest: /tmp
  tasks:
      - name: pull etc keys for tower
        synchronize: mode=pull src=/etc/awx dest={{ pulldest }}/tower.etc
        when: inventory_hostname == "192.168.33.10"

      - name: pull var lib awx for tower
        synchronize: mode=pull src=/var/lib/awx dest={{ pulldest }}/tower.var.lib
        when: inventory_hostname == "192.168.33.10"
