---
- name: Backup Tower and Restore to Second Host 
  hosts: all
  sudo: true
  vars:
    restore: no
    pulldest: /tmp
  tasks:
      - name: pull etc keys for tower
        synchronize: mode=pull src=/etc/awx dest={{ pulldest }}/tower.etc
        when: inventory_hostname == "192.168.33.10"

      - name: pull var lib awx for tower
        synchronize: mode=pull src=/var/lib/awx dest={{ pulldest }}/tower.var.lib
        when: inventory_hostname == "192.168.33.10"
        
      - name: db dump 
        shell: awx-manage dumpdata --format=json --all > {{ pulldest }}/db.json
        when: inventory_hostname == "192.168.33.10"
        
      - name: pull db for tower
        synchronize: mode=pull src=/tmp/db.json dest={{ pulldest }}/
        when: inventory_hostname == "192.168.33.10"

      - name: copy up db
        synchronize: src={{ pulldest }}/db.json dest=/tmp/
        when: inventory_hostname == "192.168.33.20"

      - name: restore 192.168.33.10 db to 192.168.33.20
        shell: awx-manage loaddata {{ pulldest }}/db.json
        when: inventory_hostname == "192.168.33.20"
