---
- name: Create a ubuntu virtual machine via vagrant
  hosts: 127.0.0.1
  sudo: true
  tasks:

    - name: change the directory path
      chdir: "C:\\tower2\\"
      local_action: vagrant destroy
